
Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/giz/giz.py", line 193, in <module>
    main()
  File "/home/ec2-user/webscrapping/giz/giz.py", line 183, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/giz/giz.py", line 58, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/idb/idb.py", line 156, in <module>
    main()
  File "/home/ec2-user/webscrapping/idb/idb.py", line 146, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/idb/idb.py", line 29, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/oecd/oecd.py", line 147, in <module>
    main()
  File "/home/ec2-user/webscrapping/oecd/oecd.py", line 137, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/oecd/oecd.py", line 29, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/paho/paho.py", line 192, in <module>
    main()
  File "/home/ec2-user/webscrapping/paho/paho.py", line 182, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/paho/paho.py", line 86, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/ungm/ungm.py", line 204, in <module>
    main()
  File "/home/ec2-user/webscrapping/ungm/ungm.py", line 179, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/ungm/ungm.py", line 75, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


Iniciando driver...
inicializando driver

haciendo paginacion...
entrando a la pagina principal: https://jobs.unops.org/Pages/ViewVacancy/VAListing.aspx
buscando el boton de paginacion con scroll
-----next page-----
durmiendo 5 segs
-----next page-----
durmiendo 5 segs
-----next page-----
durmiendo 5 segs
-----next page-----
durmiendo 5 segs
-----next page-----
durmiendo 5 segs
-----next page-----
durmiendo 5 segs
-----next page-----
durmiendo 5 segs
-----next page-----
no hay mas paginas

Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/unops/unops.py", line 202, in <module>
    main()
  File "/home/ec2-user/webscrapping/unops/unops.py", line 195, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/unops/unops.py", line 53, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.

/home/ec2-user/webscrapping/unops_interns/unops_interns.py:31: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(options=chrome_options, executable_path='C:\\chromedriver.exe')

Iniciando driver...
inicializando driver

haciendo paginacion...
entrando a la pagina principal: https://jobs.unops.org/Pages/ViewVacancy/InternshipListing.aspx
buscando el boton de paginacion con scroll
-----next page-----
no hay mas paginas

Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/unops_interns/unops_interns.py", line 202, in <module>
    main()
  File "/home/ec2-user/webscrapping/unops_interns/unops_interns.py", line 195, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/unops_interns/unops_interns.py", line 53, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


Cargando el dataset de oportunidades guardadas...
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/wbg/wbg.py", line 141, in <module>
    main()
  File "/home/ec2-user/webscrapping/wbg/wbg.py", line 131, in main
    df = load_csv(file_name)
  File "/home/ec2-user/webscrapping/wbg/wbg.py", line 29, in load_csv
    return pd.read_csv(file_name, encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.

///////////////++++++++++++++++++++++ ejecutando giz.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando idb.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando oecd.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando paho.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando ungm.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando unops.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando unops_interns.py ++++++++++++++++++++++////////////////
///////////////++++++++++++++++++++++ ejecutando wbg.py ++++++++++++++++++++++////////////////
///////////////////////++++++++++++++++++++++ FIN DE LA EJECUCION DE LOS SCRAPPERS ++++++++++++++++++++++////////////////
--------->>>>>>>>>>> Algoritmo de generacion de alertas......
leyendo oportunidades guardadas
Traceback (most recent call last):
  File "/home/ec2-user/webscrapping/pipeline.py", line 326, in <module>
    main()
  File "/home/ec2-user/webscrapping/pipeline.py", line 253, in main
    df = pd.read_csv('oportunidades.csv', encoding='utf-8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.

